/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CaseType = { 'realEstate' : null } |
  { 'willsAndEstates' : null } |
  { 'contracts' : null } |
  { 'employment' : null } |
  { 'criminal' : null } |
  { 'civilLitigation' : null } |
  { 'corporate' : null } |
  { 'family' : null };
export interface ConsultationRequest {
  'id' : string,
  'status' : ConsultationStatus,
  'caseType' : CaseType,
  'name' : string,
  'submittedAt' : Time,
  'submittedBy' : Principal,
  'description' : string,
  'email' : string,
  'phone' : string,
}
export type ConsultationStatus = { 'responded' : null } |
  { 'pending' : null } |
  { 'reviewed' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkRequestStatus' : ActorMethod<[string], ConsultationStatus>,
  'claimFirstAdmin' : ActorMethod<[], boolean>,
  'getAllRequests' : ActorMethod<[], Array<ConsultationRequest>>,
  'getAllRequestsWithPin' : ActorMethod<[string], Array<ConsultationRequest>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitConsultationRequest' : ActorMethod<
    [string, string, string, CaseType, string],
    string
  >,
  'updateRequestStatus' : ActorMethod<[string, ConsultationStatus], undefined>,
  'updateRequestStatusWithPin' : ActorMethod<
    [string, ConsultationStatus, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];