/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ConsultationStatus = IDL.Variant({
  'responded' : IDL.Null,
  'pending' : IDL.Null,
  'reviewed' : IDL.Null,
});
export const CaseType = IDL.Variant({
  'realEstate' : IDL.Null,
  'willsAndEstates' : IDL.Null,
  'contracts' : IDL.Null,
  'employment' : IDL.Null,
  'criminal' : IDL.Null,
  'civilLitigation' : IDL.Null,
  'corporate' : IDL.Null,
  'family' : IDL.Null,
});
export const Time = IDL.Int;
export const ConsultationRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : ConsultationStatus,
  'caseType' : CaseType,
  'name' : IDL.Text,
  'submittedAt' : Time,
  'submittedBy' : IDL.Principal,
  'description' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkRequestStatus' : IDL.Func([IDL.Text], [ConsultationStatus], ['query']),
  'getAllRequests' : IDL.Func([], [IDL.Vec(ConsultationRequest)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitConsultationRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, CaseType, IDL.Text],
      [IDL.Text],
      [],
    ),
  'updateRequestStatus' : IDL.Func([IDL.Text, ConsultationStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ConsultationStatus = IDL.Variant({
    'responded' : IDL.Null,
    'pending' : IDL.Null,
    'reviewed' : IDL.Null,
  });
  const CaseType = IDL.Variant({
    'realEstate' : IDL.Null,
    'willsAndEstates' : IDL.Null,
    'contracts' : IDL.Null,
    'employment' : IDL.Null,
    'criminal' : IDL.Null,
    'civilLitigation' : IDL.Null,
    'corporate' : IDL.Null,
    'family' : IDL.Null,
  });
  const Time = IDL.Int;
  const ConsultationRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : ConsultationStatus,
    'caseType' : CaseType,
    'name' : IDL.Text,
    'submittedAt' : Time,
    'submittedBy' : IDL.Principal,
    'description' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkRequestStatus' : IDL.Func(
        [IDL.Text],
        [ConsultationStatus],
        ['query'],
      ),
    'getAllRequests' : IDL.Func([], [IDL.Vec(ConsultationRequest)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitConsultationRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, CaseType, IDL.Text],
        [IDL.Text],
        [],
      ),
    'updateRequestStatus' : IDL.Func([IDL.Text, ConsultationStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };